### ISSUE TITLE
v2 Progress Tracker

### ISSUE THREAD

**Issue by bclinkinbeard** [idyll-lang/idyll-mono#2]
Migrating the list here for convenience.

- [ ] Move to a monorepo structure
- [ ] [Adopt React 16](https://github.com/facebook/react/issues/10294)
- [ ] Clean up and refine `idyll-document`, specifically the walkers
- [ ] Curate and add to the list of default components (will create a separate issue to discuss in detail)
- [ ] Remove the need for `idyll-component` and improve support for plain React components
- [ ] Ensure editor code is production-ready
- [ ] Clean up compiler related to issues mentioned below
